language: cpp
sudo: required
dist: trusty

os:
- linux
# - osx (temporari)

compiler:
- clang
# - gcc

branches:
  only:
  - master
  - develop

env:
- BUILD_TYPE=Debug
- BUILD_TYPE=Release

matrix:
 exclude:
 - os: osx
   compiler: gcc

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt593-trusty -y
- sudo apt-get update -qq
- chmod +x .travis/*/*.sh

install:
- sudo apt-get -y install qt59base
- source /opt/qt*/bin/qt*-env.sh
- .travis/${TRAVIS_OS_NAME}/install.sh

script:
- .travis/${TRAVIS_OS_NAME}/build_${BUILD_TYPE}.sh
- .travis/${TRAVIS_OS_NAME}/test_${BUILD_TYPE}.sh

after_success:
  - find AppDir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Steca*.AppImage*


addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt-5.10.1-trusty
    packages:
    - qt510base
    - xvfb
